const GET_MENULIST = 'GET_MENULIST'
const GET_SLIDERLIST = 'GET_SLIDERLIST'
const GET_MENUCONTENT = 'GET_MENUCONTENT'
const TRADEMARKSHOW = 'TRADEMARKSHOW'
const TRADEMARKHIDE = 'TRADEMARKHIDE'
const TRADEMARKSHOW_1 = 'TRADEMARKSHOW_1'
const TRADEMARKHIDE_1 = 'TRADEMARKHIDE_1'
const TRADEMARKSHOW_2 = 'TRADEMARKSHOW_2'
const TRADEMARKHIDE_2 = 'TRADEMARKHIDE_2'
const SHOWNEWSLIST = 'SHOWNEWSLIST'
const HIDENEWSLIST = 'HIDENEWSLIST'
const GET_NEWSLIST = 'GET_NEWSLIST'
const GET_NEWSPAGE = 'GET_NEWSPAGE'
const HIDENEWSPAGE = 'HIDENEWSPAGE'
const PATENT_SHOW  = 'PATENT_SHOW'
const PATENT_HIDE = 'PATENT_HIDE'
const COPYRIGHT_SHOW = 'COPYRIGHT_SHOW'
const COPYRIGHT_HIDE = 'COPYRIGHT_HIDE'
const SET_FORMDATA = 'SET_FORMDATA'

export default{
	GET_MENULIST,
	GET_SLIDERLIST,
	GET_MENUCONTENT,
	TRADEMARKSHOW,
	TRADEMARKHIDE,
	TRADEMARKSHOW_1,
	TRADEMARKHIDE_1,
	TRADEMARKSHOW_2,
	TRADEMARKHIDE_2,
	SHOWNEWSLIST,
	HIDENEWSLIST,
	GET_NEWSLIST,
	GET_NEWSPAGE,
	HIDENEWSPAGE,
	PATENT_SHOW,
	PATENT_HIDE,
	COPYRIGHT_SHOW,
	COPYRIGHT_HIDE,
	SET_FORMDATA,
}
